Issue #2 add to favourites
ita-social-projects/oos-back-sandbox-202310 pull request #8
Opened 2023-11-01 08:56 UTC by OleksSavchenko

2023-11-02 07:29 UTC, DmyMi requested changes

2023-11-02 07:29 UTC, DmyMi commented on OutOfSchool/OutOfSchool.WebApi/Services/FavouriteService.cs
> +        var newFavourite = await favouriteRepository.Create(favourite).ConfigureAwait(false);
what happens if the user and/or workshop does not exist? Or they exist but have and `isDeleted=true` (soft delete property that allows us to _delete_ something without removing it from DB). Technically it should not be possible to create such favourite records.

2023-11-03 17:58 UTC, OleksSavchenko commented on OutOfSchool/OutOfSchool.WebApi/Services/FavouriteService.cs
> +        var newFavourite = await favouriteRepository.Create(favourite).ConfigureAwait(false);
Done

2023-11-10 12:03 UTC, DmyMi approved these changes

2023-11-10 12:03 UTC, merged